### ISSUE TITLE
Error login with biometrics

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#374]
Login with biometrics produces an error getting the keychain, therefore myWitWallet does not correctly sign transactions.

Signing transactions needs the password hash to decrypt the xprv, either we delete the biometrics #375  functionality or ask the user to input the password to send transactions #379 . Using a switch in settings to enable using biometrics cannot be an option as the library `local_auth` does not return a unique identifier to encrypt the xprv.

**Comment by drcpu-github** [comment]
This certainly explains the value transfers I (sometimes) see in the explorer backend without a signature (and which thus fail the regular expression validation). I tried root causing it, but could not find the reason. This also explains why restoring a wallet from the seed solves the issue since you don't login using biometrics at that point. Good catch!
