### ISSUE TITLE
Tag UTXOS as pending to avoid using the same UTXOS from a pending vtt

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#394]
Currently the user can only send one `vtt` at a time. The UTXOS are reused until the transaction is mined.

We should mark used UTXOS as `pending` or `used` to avoid using UTXOS from an already pending transaction, and thus allowing more than one pending transaction to be resolved at the same time.

**Comment by aesedepece** [comment]
As you can imagine, a similar pattern exists in `witnet-rust`. From implementing that back in 2018/2019, we learnt that marking the UTXOs as used is sometimes not enough. This is to allow recovering the ability of spending UTXOs even if there's a rollback.

Instead of flagging them with a boolean, it is always better to flag them with the timestamp. The timestamp should initially be set to 0, and updated with the current timestamp as soon as the UTXO is used. Then the used vs. unused status is derived on the fly by checking if the current timestamp minus the specific UTXO timestamp is higher than a threshold, i.e. if the UTXO timestamp is too recent, we consider it "used".

This of course assumes that UTXOs are deleted as soon as the transaction spending them is confirmed.

Hence the lifetime of a UTXO goes like this:
1. Discovered: UTXO is stored and its timestamp is set to 0
2. Spent: UTXO timestamp is updated to the current timestamp
3. Destroyed upon confirmation: UTXO is removed from database

**Comment by aesedepece** [comment]
For reference, `witnet-rust` considers an UTXO as pending for 450 seconds (10 blocks). It is called the `pending_transactions_timeout_seconds`.

The consequence is that if you create a first transaction and after 450 seconds it is not included into a block, it will become spendable again from the point of view of the node/wallet, and a subsequent transaction could fall into double-spend.

The eventual confirmation of either of those two transactions will eventually sanitize the UTXO set.

I think we lack the information needed to assess whether MWW should use a shorter or longer timeout than 450 seconds, but it seems like a good starting point, provided that 99.99% of the VTTs are confirmed in way less than that period always that they pay non-zero fees (priority > 0), and we don't expect this to change anytime soon.

This however made me realize that instead of tagging the UTXOs with the timestamp of the moment in which you are spending them, it could be a better idea to tag them with the timestamp before which we don't want them to become spendable again (a future timestamp that is decided at the time you include the UTXO into a transaction). This enables using different timeout periods depending on the priority chosen by the transaction, i.e. wait longer to allow re-spending an UTXO if it was spent in a transaction with low priority.

That construction would prevent double spending UTXOs used in transactions with zero fees, which is something that is indeed happening, albeit only to the _stinky_ users out there like myself. However, in a future scenario in which the chain becomes crowded, VTTs start to pile up in the mempool, and the cost of transaction priority starts to grow, this model in which the timeout depends on priority may really prove to be useful to prevent accidental double-spending.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/my-wit-wallet/394?planning-poker) with Zenhub @aesedepece @gabaldon @guidiaz @aeweda

**Comment by parodyBit** [comment]
We should not need a timeout since we are getting the UTXOs directly from the Explorer.
a check of which transactions are "pending" should be enough to mark those UTXOs as "used".
 during the next sync, if a previous transaction that was pending is now "unknown hash", the UTXO would be spendable again. if the transaction settles to "mined" then the UTXO is removed like normal.
