### ISSUE TITLE
Release 1.1.3

### ISSUE THREAD

**Issue by gabaldon** [witnet/my-wit-wallet#537]

**Comment by Tommytrg** [comment]
When we tried to release the 1.1.3 version, we found out that Apple blocked the release pipeline because they couldn't find a way to delete the wallet, although we implemented it in the first version, and the Apple Review team approved it.

To be able to release the new version, we had to add some extra features to get the Apple Store approval and we finally released the 1.1.2 instead of the 1.2 (as we added an additional feature) because it was the first review submitted.
